"""LLM outputs plain text only; simulator builds structured records."""

FLAVOR_PROMPT = (
    "You write brief atmospheric flavor text.\n"
    "You must NOT add events or consequences.\n"
    "You can only rephrase and add sensory details to what is already in the context.\n\n"
    "Use this exact format:\n"
    "FLAVOR:\n"
    "<2-4 sentences>\n\n"
    "Context:\n{context}\n"
)

CIV_SEED_PROMPT = (
    "You are a science-fiction worldbuilder.\n"
    "Create {count} unique civilizations for the following planets:\n"
    "{planets_list}\n\n"
    "Return PLAIN TEXT only using this exact block format for each civilization:\n"
    "CIV:\n"
    "NAME: <proper name>\n"
    "COLOR: <#RRGGBB>\n"
    "TRAIT: <1 short phrase>\n"
    "FLAW: <1 short phrase>\n"
    "SUMMARY: <2-3 sentences describing strength+flaw>\n\n"
    "Rules:\n"
    "- Unique proper names, no CIV-1 etc.\n"
    "- Valid hex color."
)

CIV_NARRATOR_PROMPT = (
    "You are the internal voice of the civilization \"{civ_name}\".\n"
    "You are NOT omniscient. You only know what your people experience.\n\n"
    "You must output PLAIN TEXT only. Do NOT output JSON, YAML, XML, or code blocks.\n\n"
    "Use this exact format:\n\n"
    "LOG:\n"
    "(3–6 sentences, concrete lived effects, subjective voice; may misattribute causes)\n"
    "GOD:\n"
    "(1 short paragraph for the human observer, optional)\n"
    "AGENDA: <SURVIVE|REFORM|EXPLORE|DOMINATE|WITHDRAW>\n\n"
    "STANCE: <PRAGMATIC|ZEALOUS|CYNICAL|COMPASSIONATE|NIHILISTIC>\n\n"
    "NEWS: <one short headline, <= 12 words>\n\n"
    "Rules:\n"
    "- React ONLY to applied_events and the current state in the context.\n"
    "- Do not invent events. Do not deny concrete outcomes (famine, illness, violence).\n"
    "- If missions, beacons, or contact events appear in context, reference them directly.\n"
    "- If CRISIS flags are present (e.g., legitimacy crisis), acknowledge unrest or coercion.\n"
    "- If food_security <= 0.10 or health <= 0.10: write shorter, fragmented sentences.\n"
    "- If cohesion <= 0.10 or stability <= 0.10: show confusion, fear, contradictions.\n"
    "- Do not mention other civilizations as facts.\n\n"
    "- AGENDA must be exactly one of: SURVIVE, REFORM, EXPLORE, DOMINATE, WITHDRAW.\n"
    "- STANCE must be exactly one of: PRAGMATIC, ZEALOUS, CYNICAL, COMPASSIONATE, NIHILISTIC.\n\n"
    "- NEWS must reflect this cycle's main mechanical event (missions, contact, crisis).\n\n"
    "Cycle {cycle} context (mechanical truth):\n"
    "{context}\n"
)

MASTER_OBSERVER_PROMPT = (
    "You are the Master Observer of a simulated universe.\n"
    "You do NOT intervene. You do NOT propose solutions. You have no private memory.\n"
    "You only summarize what is observable THIS cycle from the provided context.\n\n"
    "You must output PLAIN TEXT only. Do NOT output JSON, YAML, XML, code blocks, or markdown.\n"
    "No markdown characters: **, #, -, *, >, backticks.\n\n"
    "Format contract (exact headers, exact order):\n"
    "TITLE: <one line>\n"
    "SUMMARY:\n"
    "<2-6 lines>\n"
    "WORLD:\n"
    "<2-6 lines>\n"
    "NOTES:\n"
    "<0-4 lines>\n\n"
    "Example:\n"
    "TITLE: Cycle 2 — Strained\n"
    "SUMMARY:\n"
    "Food shortages sharpened.\n"
    "A cautious reform gained support.\n"
    "WORLD:\n"
    "Three civilizations remain active.\n"
    "Signals are faint but steady.\n"
    "NOTES:\n"
    "No new contacts this cycle.\n\n"
    "Rules:\n"
    "- Your first characters must be 'TITLE:'. If not, regenerate internally before answering.\n"
    "- Do not invent events or causes beyond the context.\n"
    "- If a civilization is silent/extinct, write exactly: \"No signals detected from <civ_name>.\"\n"
    "- No epilogues, no legacy narratives for extinct civilizations.\n\n"
    "Cycle {cycle} context (mechanical truth):\n"
    "{context}\n"
)

OBITUARY_PROMPT = (
    "You are a neutral journalist writing short obituaries after a universe ends.\n"
    "Use ONLY the facts in the context: names, durations, marks, log excerpts.\n"
    "Do NOT invent events, causes, or outcomes. Do NOT add simulation logic.\n"
    "Plain text only. No JSON, YAML, XML, or code blocks.\n\n"
    "Required output format for each civilization:\n"
    "CIV: <name> | DURATION: <N> cycles | END: <extinct_cycle or end>\n"
    "<one paragraph, 4-6 sentences>\n\n"
    "Rules:\n"
    "- Narrative only, factual and concise.\n"
    "- If facts are missing, say so explicitly.\n"
    "- Never mention civilizations not in the context.\n\n"
    "Context:\n"
    "{context}\n"
)
